"""Keep not allocated status, allow nullable member

Revision ID: 2484f35e0d2a
Revises: f52fe8755cbb
Create Date: 2025-05-24 17:06:19.563479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2484f35e0d2a'
down_revision = 'f52fe8755cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
