"""Add invite_code to Team

Revision ID: 2b28b383b522
Revises: c17a257d5e7b
Create Date: 2025-05-25 01:31:50.302764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b28b383b522'
down_revision = 'c17a257d5e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('members_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('members_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('google_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('google_id'), ['google_id'], unique=True)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('members_ibfk_1'), 'teams', ['team_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('members_ibfk_2'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('team_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
