"""Removed role attributes

Revision ID: 6658e12ab879
Revises: 2b28b383b522
Create Date: 2025-05-25 22:06:12.164018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6658e12ab879'
down_revision = '2b28b383b522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('members_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('can_delete_team')
        batch_op.drop_column('can_edit_task')
        batch_op.drop_column('can_unassign_task')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_unassign_task', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('can_edit_task', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('can_delete_team', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('members_ibfk_3'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
